name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Start Webdriver
        run: |
          # Set up the webdriver for the browser you want to test
          # For example, for Chrome:
          CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
          curl -sS -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          sudo unzip -qq /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Tests
        run: |
          # Run the test cases using pytest or any other testing framework
          python  -v test/

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: results.txt
          path: report/
