name: Selenium Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Start web driver
      run: |
        wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE
        LATEST=$(cat LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        export PATH=$PATH:/github/workspace

         - name: Run Tests
        run: |
          # Run the test cases using pytest or any other testing framework
          pytest  -v test/
        - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: results.txt
          path: report/
